SELECT TOP (1000) [Car_ID]
      ,[Brand]
      ,[Model]
      ,[Year]
      ,[Fuel_Type]
      ,[Transmission]
      ,[Color]
      ,[Owner_Type]
      ,[Mileage_kmpl]
      ,[Price_Lakh]
      ,[Provider]
      ,[Policy_Number]
      ,[Expiry_Date]
      ,[Status]
      ,[Owner_Name]
      ,[Contact]
      ,[City]
      ,[Purchase_Year]
      ,[Sale_Price_Lakh]
      ,[Sale_Date]
      ,[Buyer_Name]
      ,[Service_Type]
      ,[Service_Date]
      ,[Service_Cost]
      ,[Service_Center]
  FROM [car].[dbo].[MASTER_CAR_DATA]
